"""baseline_inicial

Revision ID: 2fd056b77553
Revises: 
Create Date: 2026-07-16 16:43:46.866210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd056b77553'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_produto_id'), 'categorias_produto', ['id'], unique=False)
    op.create_table('cfop_natureza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=False),
    sa.Column('natureza', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfop_natureza_cfop'), 'cfop_natureza', ['cfop'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('bling_id', sa.BigInteger(), nullable=True),
    sa.Column('bling_updated_at', sa.DateTime(), nullable=True),
    sa.Column('bling_pending_sync', sa.Boolean(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('fantasia', sa.String(length=200), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('isento_ie', sa.Boolean(), nullable=True),
    sa.Column('indicador_ie', sa.String(length=20), nullable=True),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=True),
    sa.Column('situacao', sa.String(length=1), nullable=True),
    sa.Column('iss_retido', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bling_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('bling_id', sa.BigInteger(), nullable=True),
    sa.Column('bling_updated_at', sa.DateTime(), nullable=True),
    sa.Column('bling_pending_sync', sa.Boolean(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('fantasia', sa.String(length=200), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('isento_ie', sa.Boolean(), nullable=True),
    sa.Column('indicador_ie', sa.String(length=20), nullable=True),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=True),
    sa.Column('situacao', sa.String(length=1), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bling_id')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('marcas_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_marcas_produto_id'), 'marcas_produto', ['id'], unique=False)
    op.create_table('nfe_distribuidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('dh_emi', sa.String(length=30), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('emitente_nome', sa.String(length=300), nullable=True),
    sa.Column('emitente_cnpj', sa.String(length=20), nullable=True),
    sa.Column('destinatario_nome', sa.String(length=300), nullable=True),
    sa.Column('destinatario_cnpj', sa.String(length=20), nullable=True),
    sa.Column('nsu', sa.String(length=20), nullable=True),
    sa.Column('schema_nfe', sa.String(length=50), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfe_distribuidas_chave_acesso'), 'nfe_distribuidas', ['chave_acesso'], unique=True)
    op.create_index(op.f('ix_nfe_distribuidas_id'), 'nfe_distribuidas', ['id'], unique=False)
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_contas_id'), 'plano_contas', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('permissoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('contas_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'VENCIDO', 'CANCELADO', 'BAIXA_SOLICITADA', 'EXCLUIDO', name='statusconta'), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('numero_documento', sa.String(length=30), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=True),
    sa.Column('plano_conta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['plano_conta_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_pagar_data_pagamento'), 'contas_pagar', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_contas_pagar_data_vencimento'), 'contas_pagar', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_pagar_fornecedor_id'), 'contas_pagar', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_id'), 'contas_pagar', ['id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_plano_conta_id'), 'contas_pagar', ['plano_conta_id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_status'), 'contas_pagar', ['status'], unique=False)
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=500), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=500), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('senha_admin', sa.String(length=100), nullable=True),
    sa.Column('senha_lembrete', sa.String(length=200), nullable=True),
    sa.Column('bling_token', sa.String(length=200), nullable=True),
    sa.Column('bling_client_id', sa.String(length=200), nullable=True),
    sa.Column('bling_client_secret', sa.String(length=200), nullable=True),
    sa.Column('bling_refresh_token', sa.String(length=200), nullable=True),
    sa.Column('bling_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('bling_webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('bling_api_key_v2', sa.String(length=100), nullable=True),
    sa.Column('bling_desabilitado', sa.Boolean(), nullable=True),
    sa.Column('sicoob_client_id', sa.String(length=200), nullable=True),
    sa.Column('sicoob_token', sa.String(length=3000), nullable=True),
    sa.Column('sicoob_conta_corrente', sa.String(length=30), nullable=True),
    sa.Column('sicoob_beneficiario', sa.String(length=20), nullable=True),
    sa.Column('sicoob_cert_path', sa.String(length=500), nullable=True),
    sa.Column('sicoob_cert_key_path', sa.String(length=500), nullable=True),
    sa.Column('sicoob_cert_password', sa.String(length=100), nullable=True),
    sa.Column('sicoob_cert_base64', sa.Text(), nullable=True),
    sa.Column('sicoob_cert_key_base64', sa.Text(), nullable=True),
    sa.Column('sicoob_cert_id', sa.Integer(), nullable=True),
    sa.Column('smtp_host', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=200), nullable=True),
    sa.Column('smtp_password', sa.String(length=200), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=200), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=200), nullable=True),
    sa.Column('email_auto_enviar', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria_servico_padrao_id', sa.Integer(), nullable=True),
    sa.Column('notaas_api_key', sa.Text(), nullable=True),
    sa.Column('aliquota_iss', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('aliquota_federal', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('aliquota_estadual', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('aliquota_municipal', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('nfe_aliquota_federal', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('nfe_aliquota_estadual', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('notaas_ambiente', sa.String(length=1), nullable=False),
    sa.Column('serie_nfe', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_nfe', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_nfse', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_pedido', sa.Integer(), nullable=True),
    sa.Column('ultimo_codigo_cliente', sa.Integer(), nullable=True),
    sa.Column('ultimo_codigo_fornecedor', sa.Integer(), nullable=True),
    sa.Column('ultimo_codigo_produto', sa.Integer(), nullable=True),
    sa.Column('cert_path', sa.String(length=500), nullable=True),
    sa.Column('cert_password', sa.String(length=100), nullable=True),
    sa.Column('cert_base64', sa.Text(), nullable=True),
    sa.Column('cert_id', sa.Integer(), nullable=True),
    sa.Column('cert_validade', sa.Date(), nullable=True),
    sa.Column('nfe_ultnsu', sa.String(length=20), nullable=True),
    sa.Column('cfop_padrao', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_servico_padrao_id'], ['categorias_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('bling_id', sa.BigInteger(), nullable=True),
    sa.Column('bling_updated_at', sa.DateTime(), nullable=True),
    sa.Column('bling_pending_sync', sa.Boolean(), nullable=True),
    sa.Column('equipamento', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('defeito_relatado', sa.Text(), nullable=True),
    sa.Column('servicos_executados', sa.Text(), nullable=True),
    sa.Column('pecas_utilizadas', sa.Text(), nullable=True),
    sa.Column('valor_servico', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_pecas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'FINALIZADA', 'CANCELADA', name='statusos'), nullable=True),
    sa.Column('tecnico', sa.String(length=200), nullable=True),
    sa.Column('autorizado_por', sa.String(length=200), nullable=True),
    sa.Column('numero_requisicao', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bling_id')
    )
    op.create_index(op.f('ix_ordens_servico_cliente_id'), 'ordens_servico', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_status'), 'ordens_servico', ['status'], unique=False)
    op.create_table('pedidos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'FATURADO', 'PRE_VENDA', 'CANCELADO', name='statuspedido'), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('tipo_pedido', sa.String(length=20), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('gerar_boleto', sa.Boolean(), nullable=True),
    sa.Column('terminos_boleto', sa.Text(), nullable=True),
    sa.Column('pedido_agrupado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['pedido_agrupado_id'], ['pedidos_venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_venda_cliente_id'), 'pedidos_venda', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_venda_id'), 'pedidos_venda', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_venda_numero'), 'pedidos_venda', ['numero'], unique=True)
    op.create_index(op.f('ix_pedidos_venda_status'), 'pedidos_venda', ['status'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('origem', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('peso_liq', sa.Float(), nullable=True),
    sa.Column('peso_bruto', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('profundidade', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('estoque', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('situacao', sa.String(length=1), nullable=False),
    sa.Column('bling_id', sa.BigInteger(), nullable=True),
    sa.Column('bling_updated_at', sa.DateTime(), nullable=True),
    sa.Column('bling_pending_sync', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('codigo_lc116', sa.String(length=10), nullable=True),
    sa.Column('codigo_tributacao_municipal', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_produto.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas_produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bling_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('bling_id', sa.BigInteger(), nullable=True),
    sa.Column('bling_updated_at', sa.DateTime(), nullable=True),
    sa.Column('bling_pending_sync', sa.Boolean(), nullable=True),
    sa.Column('periodicidade', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('mes_vencimento', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('valor_revenda', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bling_id')
    )
    op.create_index(op.f('ix_assinaturas_cliente_id'), 'assinaturas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_assinaturas_data_fim'), 'assinaturas', ['data_fim'], unique=False)
    op.create_index(op.f('ix_assinaturas_id'), 'assinaturas', ['id'], unique=False)
    op.create_table('nfe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('serie', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=50), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('modelo', sa.Integer(), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=100), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('finalidade', sa.String(length=30), nullable=True),
    sa.Column('indicador_presenca', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('base_calculo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_icms', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('mensagem_retorno', sa.Text(), nullable=True),
    sa.Column('aliquota_federal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliquota_estadual', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_nfe_cliente_id'), 'nfe', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_nfe_status'), 'nfe', ['status'], unique=False)
    op.create_table('nfse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('codigo_verificacao', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('mensagem_retorno', sa.Text(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=100), nullable=True),
    sa.Column('regime_especial', sa.String(length=100), nullable=True),
    sa.Column('municipio_codigo', sa.String(length=10), nullable=True),
    sa.Column('municipio_nome', sa.String(length=100), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('iss_retido', sa.Boolean(), nullable=True),
    sa.Column('aliquota_iss', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliquota_federal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliquota_estadual', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliquota_municipal', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfse_cliente_id'), 'nfse', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_nfse_status'), 'nfse', ['status'], unique=False)
    op.create_table('produto_composicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_pai_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_padrao', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['produto_pai_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_composicao_id'), 'produto_composicao', ['id'], unique=False)
    op.create_table('produto_variacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome_variacao', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('preco_adicional', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_produto_variacoes_id'), 'produto_variacoes', ['id'], unique=False)
    op.create_table('assinaturas_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assinatura_id', sa.Integer(), nullable=False),
    sa.Column('valor_anterior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_revenda_anterior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantidade_anterior', sa.Integer(), nullable=True),
    sa.Column('dia_vencimento_anterior', sa.Integer(), nullable=True),
    sa.Column('valor_novo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_revenda_novo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantidade_novo', sa.Integer(), nullable=True),
    sa.Column('dia_vencimento_novo', sa.Integer(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_historico_id'), 'assinaturas_historico', ['id'], unique=False)
    op.create_table('contas_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'VENCIDO', 'CANCELADO', 'BAIXA_SOLICITADA', 'EXCLUIDO', name='statusconta'), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('nosso_numero', sa.String(length=30), nullable=True),
    sa.Column('boleto_emitido', sa.Boolean(), nullable=True),
    sa.Column('boleto_url', sa.String(length=500), nullable=True),
    sa.Column('boleto_txid', sa.String(length=50), nullable=True),
    sa.Column('numero_documento', sa.String(length=30), nullable=True),
    sa.Column('api_nosso_numero', sa.String(length=30), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('motivo_baixa', sa.String(length=100), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=True),
    sa.Column('plano_conta_id', sa.Integer(), nullable=True),
    sa.Column('nfse_id', sa.Integer(), nullable=True),
    sa.Column('email_enviado', sa.Boolean(), nullable=True),
    sa.Column('data_envio_email', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['nfse_id'], ['nfse.id'], ),
    sa.ForeignKeyConstraint(['plano_conta_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nosso_numero')
    )
    op.create_index(op.f('ix_contas_receber_boleto_emitido'), 'contas_receber', ['boleto_emitido'], unique=False)
    op.create_index(op.f('ix_contas_receber_cliente_id'), 'contas_receber', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contas_receber_data_recebimento'), 'contas_receber', ['data_recebimento'], unique=False)
    op.create_index(op.f('ix_contas_receber_data_vencimento'), 'contas_receber', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_receber_id'), 'contas_receber', ['id'], unique=False)
    op.create_index(op.f('ix_contas_receber_plano_conta_id'), 'contas_receber', ['plano_conta_id'], unique=False)
    op.create_index(op.f('ix_contas_receber_status'), 'contas_receber', ['status'], unique=False)
    op.create_table('nfe_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfe_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('item_pai_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('unidade', sa.String(length=6), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_pai_id'], ['nfe_itens.id'], ),
    sa.ForeignKeyConstraint(['nfe_id'], ['nfe.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfse_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfse_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('codigo_servico', sa.String(length=20), nullable=True),
    sa.Column('tributacao_municipal', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['nfse_id'], ['nfse.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('variacao_id', sa.Integer(), nullable=True),
    sa.Column('item_pai_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['item_pai_id'], ['pedidos_venda_itens.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venda.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['variacao_id'], ['produto_variacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_venda_itens_id'), 'pedidos_venda_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_venda_itens_id'), table_name='pedidos_venda_itens')
    op.drop_table('pedidos_venda_itens')
    op.drop_table('nfse_itens')
    op.drop_table('nfe_itens')
    op.drop_index(op.f('ix_contas_receber_status'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_plano_conta_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_data_vencimento'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_data_recebimento'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_cliente_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_boleto_emitido'), table_name='contas_receber')
    op.drop_table('contas_receber')
    op.drop_index(op.f('ix_assinaturas_historico_id'), table_name='assinaturas_historico')
    op.drop_table('assinaturas_historico')
    op.drop_index(op.f('ix_produto_variacoes_id'), table_name='produto_variacoes')
    op.drop_table('produto_variacoes')
    op.drop_index(op.f('ix_produto_composicao_id'), table_name='produto_composicao')
    op.drop_table('produto_composicao')
    op.drop_index(op.f('ix_nfse_status'), table_name='nfse')
    op.drop_index(op.f('ix_nfse_cliente_id'), table_name='nfse')
    op.drop_table('nfse')
    op.drop_index(op.f('ix_nfe_status'), table_name='nfe')
    op.drop_index(op.f('ix_nfe_cliente_id'), table_name='nfe')
    op.drop_table('nfe')
    op.drop_index(op.f('ix_assinaturas_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_data_fim'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_cliente_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_venda_status'), table_name='pedidos_venda')
    op.drop_index(op.f('ix_pedidos_venda_numero'), table_name='pedidos_venda')
    op.drop_index(op.f('ix_pedidos_venda_id'), table_name='pedidos_venda')
    op.drop_index(op.f('ix_pedidos_venda_cliente_id'), table_name='pedidos_venda')
    op.drop_table('pedidos_venda')
    op.drop_index(op.f('ix_ordens_servico_status'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_cliente_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_contas_pagar_status'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_plano_conta_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_fornecedor_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_data_vencimento'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_data_pagamento'), table_name='contas_pagar')
    op.drop_table('contas_pagar')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_plano_contas_id'), table_name='plano_contas')
    op.drop_table('plano_contas')
    op.drop_index(op.f('ix_nfe_distribuidas_id'), table_name='nfe_distribuidas')
    op.drop_index(op.f('ix_nfe_distribuidas_chave_acesso'), table_name='nfe_distribuidas')
    op.drop_table('nfe_distribuidas')
    op.drop_index(op.f('ix_marcas_produto_id'), table_name='marcas_produto')
    op.drop_table('marcas_produto')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_cfop_natureza_cfop'), table_name='cfop_natureza')
    op.drop_table('cfop_natureza')
    op.drop_index(op.f('ix_categorias_produto_id'), table_name='categorias_produto')
    op.drop_table('categorias_produto')
    # ### end Alembic commands ###
